### PR TITLE
fixed finance contacts example to use numeric account codes

### PR DESCRIPTION
**Pull request by rjaus**
## Description
Updates finance contacts example to be in line with API

## Release Notes
No relevant changes for users

## Types of Changes

- [ x ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by rdemarco-xero — APPROVED** [review]
Looks good

**Review by rdemarco-xero — CHANGES_REQUESTED** [review]
Just caught that AccountCodes is a string array. Should the examples be in quotes since they are integers?

**Comment by rjaus** [comment]
@rdemarco-xero fair call.  They are now explicitly strings.  I've also added an additional example which is a valid account code, but contains alphanumeric characters.  Which is still valid.

Which goes back the original debate.  The initial example was technically valid, but in practice highly unusual.

The new examples are what a user would commonly expect, plus an example of alphanumeic (and special characters) account code usage.

**Review by rdemarco-xero — APPROVED** [review]
Looks good!

**Pull request merged**
