### PR TITLE
Add API SDK Support for LumpSumW and SCHEDULE4MANUAL tax type

### PR DESCRIPTION
**Pull request by amanda-li128**
## Description

JIRA: https://xero.atlassian.net/browse/AUP-5483
Add API SDK Support for LumpSumW and SCHEDULE4MANUAL tax type
## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by amanda-li128** [comment]
Do not merge until we release LSW to Prod

**Review by rdemarco-xero — CHANGES_REQUESTED** [review]
Looks good. Only request is that you bump the versions across all the yaml files from '2.16.1' to '2.16.2'.

**Comment by RettBehrens** [comment]
Thanks. Ditto on the version bump request and please ping us when you've released LSW to Prod

**Comment by amanda-li128** [comment]
Version updated. Thanks  @RettBehrens @rdemarco-xero

**Review by RettBehrens — APPROVED** [review]

**Review by RettBehrens — APPROVED** [review]

**Pull request merged**
