### PR TITLE
journal number, from string to number

### PR DESCRIPTION
**Pull request by SerKnight**
Found by community member: https://github.com/XeroAPI/xero-node/issues/412

A deserialization is being effected for node sdk.. I can fix in the SDK itself, but this seems like an API wide type fix that should propagate through all sdks?

### CODE REVIEW

**Comment by SerKnight** [comment]
WIP

**Comment by SerKnight** [comment]
I've verified the fix in node. Will check Ruby on Monday - want to double check and see if this is deserializing correctly in java/net the way it is now ( string, not number )

**Comment by SerKnight** [comment]
Ah - thats what I was looking for. Theres no decimal places. I'll re work this / test through and can go through during Hero mtg.

**Comment by SidneyAllen** [comment]
@SerKnight - i've change the JournalNumber to an integer and will merge this PR.

**Pull request merged**
