### PR TITLE
updateEmployee singular not supported by API

### PR DESCRIPTION
**Pull request by SerKnight**
After a bit of clarity searching in Xero ( Employees outside of 'Payroll' are essentially a Contact with a special Employee Type.. However the API endpoint for `https://api.xero.com/api.xro/2.0/Employees` only supports batch updates and there is no support for calls structured as single Employee(Contact) updates ie: `https://api.xero.com/api.xro/2.0/Employees/{UUID}`

> https://developer.xero.com/documentation/api/employees#POST
#### Use this method to create or update one or more employee records.
```json
POST https://api.xero.com/api.xro/2.0/Employees
{
  "Employees": [
    {
      "FirstName": "Joey",
      "LastName": "Bloggs"
    }
  ]
}
```

Removing this endpoint to eliminate confusion. The batch endpoint works *albeit a bit wonky*  - Xero uses the "First Name /// Last Name" as the unique identifier to pass into the array of Contact/Employees to update.

### CODE REVIEW

**Comment by SerKnight** [comment]
Discovered by pairing w/ Rett through this PR https://github.com/XeroAPI/xero-node-oauth2-app/pull/38/files

**Comment by SidneyAllen** [comment]
@SerKnight - maybe it should not be removed.  

If we are being consistent - then we should replace "updateEmployee" with updateOrCreateEmployees.

Thoughts?

**Comment by SerKnight** [comment]
Thanks team - Sid I know we said you will be gatekeeper for merging these repo PR's but this one looks well reviewed and tested.

**Comment by SerKnight** [comment]
updateOrCreateEmployees exists and is working - updateEmployee remvoed!

**Pull request merged**
