### PR TITLE
[STA-905] added 9% tax rates for Singapore

### PR DESCRIPTION
**Pull request by GlenXero**
## Description
- Add 9% tax rates for Singapore

## Release Notes
- Compliance with new IRAS GST rate of 9% starting 2024

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by MichaelTranXero** [comment]
LGTM

**Review by MichaelTranXero — APPROVED** [review]
LGTM

**Comment by GlenXero** [comment]
Requirements under review, please don't merge yet.

**Review by rdemarco-xero — APPROVED** [review]

**Comment by rdemarco-xero** [comment]
Received confirmation from @GlenXero the review was successful

**Pull request merged**
