### PR TITLE
Revert "Add DueDate to CreditNotes"

### PR DESCRIPTION
**Pull request by SidneyAllen**
Reverts XeroAPI/Xero-OpenAPI#319

### CODE REVIEW

**Comment by MatthewSteeples** [comment]
Hi @SidneyAllen,

Did we miss something in our PR?

Thanks,
Matthew

**Comment by MatthewSteeples** [comment]
Ah, apart from replacing Invoice with CreditNote 😣

**Comment by SidneyAllen** [comment]
@MatthewSteeples - I needed to confirm adding this property as it's not in our current docs (though it is in the json example response).  

Confirmed now and in release 2.5.0

**Comment by MatthewSteeples** [comment]
Great. We're just about to start testing our new OpenAPI based version of Movemybooks, so we'll send differences as we find them 🙂

**Pull request merged**
