### PR TITLE
Add 2 currencies

### PR DESCRIPTION
**Pull request by SerKnight**
* Add 2 missing currencies that are part of a legacy data issue reported in `xero-ruby` https://github.com/XeroAPI/xero-ruby/issues/76

* @SidneyAllen - have an issue with not being able to access the `_TRY` currency due to the underscore not matching ruby conventions. Might be some history to that I need to work around.. context below.

XeroRuby::Accounting::CurrencyCode::_TRY
`error`

### CODE REVIEW

**Comment by SerKnight** [comment]
Well did more reading and found that is actually a native vendor extension that is picked up automatically w/out need to write mustache template code: https://openapi-generator.tech/docs/templating/

Will clean up this PR once I can validate.

**Comment by SerKnight** [comment]
Okay put the extensions back and just added the two new currencies.

The `TRY` currency is the only problem now. I see the following:
Enum -> x-enum-varnames:
`TRY` -> `_TRY`
`""` -> `_EMPTY`

Is the TRY constant breaking elsewhere? I think I understand why empty string x-enum-varname is set to _EMPTY, but think I need clarification.. This is due to the ruby reported issue that an org they are using has the `Turkish lira`  TRY currency.

**Comment by SidneyAllen** [comment]
@SerKnight - TRY as an enum does break PHP.

**Comment by SerKnight** [comment]
Probably not a high trafficked currency but could call it `LIRA` instead?

**Comment by SidneyAllen** [comment]
@SerKnight - x-enum-varnames is needed AFAIK.  

If I recall it is picked up in the OpenAPI codegen, so isn't part of our templates.  I didn't create the vendor extension, the community did to address issues around enums that conflict with reserved words in different languages.

PR looks find

**Pull request merged**
