### PR TITLE
Created POST specification for /projects

### PR DESCRIPTION
**Pull request by EM-John**
Implemented POST for /projects. Implemented "NewProject" schema for request body content.

### CODE REVIEW

**Comment by SidneyAllen** [comment]
Thanks for the PR - we will need to review and test building with our SDK .  This will take some time and we have some other work with the SDKs we need to address first

**Comment by SidneyAllen** [comment]
Hi @EM-John 

I've finished updating the Projects OpenAPI spec and have tested it with our Java SDK.  

There are a few issues at the API level that I've asked the team to look into, so I'll be commenting out endpoint/methods that don't currently function for JSON.

createTask
updateTask
deleteTask

**Comment by EM-John** [comment]
Thanks @SidneyAllen.

Should I bother to make PRs in the future? The Projects API is important to me and I anxiously await the day it's complete. Would love to help accelerate it where I can. I made this small PR instead of a larger one to make sure I was doing things correctly.

**Comment by SidneyAllen** [comment]
Hey @EM-John 

We appreciate your taking a first cut at this.

Yes PRs are welcome.  A fair amount of caution needs to be exercised as these specs are used to build our 5 (soon to be 6) language SDKs.

We have a process for building NEW specs.  We create the OAS and model them after existing patterns around components, etc, then we actually build our Java SDK with the new spec, make API calls with them and write unit tests to confirm objects are being serialized and deserialized properly.  Only then do we consider them "in release".

We've done all that with the Projects yaml file and have rolled it out to our Java SDK, with others to languages to follow.

Based on feedback from developers we'll continue to iterate on these and PRs are welcome.

As noted above, 3 operations on "tasks" endpoint are not functioning properly.  This is an issue at the API level and I've raised it with those teams - no ETA on when that will be addressed based on current roadmap and priorities.

**Comment by EM-John** [comment]
@SidneyAllen sounds good! Hope my comments didn't come across as rude or angry. I was actually nervous to send a PR to begin with because I didn't want to submit something horribly wrong (imposter syndrome in full swing here). Wanted to make sure I was actually in-line with your process before submitting more work.

**Comment by SidneyAllen** [comment]
@EM-John - All good from my end!  Appreciate you taking the time to contribute.   As someone with 20 years exp. there is always something new to learn and new opportunities for me to feel like an "imposter" as well.  

This is all new and we are figuring it out together. :-)

**Pull request closed without merging**
